---
- hosts: all
  tasks:
  - name: Install required packages
    apt:
      name:
        - python3
        - python3-pip
        - python3-tk
      state: present
  - name: Install pysamba package
    pip:
      name: pysamba
      state: present
  - name: Write Netplan configuration
    copy:
      content: |
        network:
          version: 2
          renderer: networkd
          ethernets:
            eth0:
              dhcp4: no
              addresses: [{{ ipaddr }}/{{ subnet }}]
              gateway4: {{ gateway }}
              nameservers: {{ domain }}
                addresses: [{{ dnssrv }}]
      dest: /etc/netplan/config.yaml
  - name: Apply Netplan configuration
    command: netplan apply
  - name: Create Samba AD DC configuration
    template:
      src: samba_ad_dc.conf.j2
      dest: /etc/samba/smb.conf
  - name: Provision Samba AD DC
    command: samba-tool domain provision --use-rfc2307 --realm={{ domain }} --domain={{ domain }} --adminpass={{ password }}
  - name: Enable and start Samba AD DC service
    service:
      name: samba-ad-dc
      state: started
      enabled: true
