---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create an Ubuntu VM on VirtualBox
    virtualbox:
      name: ansible-test-vm
      ostype: Ubuntu_64
      memory: 512
      cpus: 1
      state: running
      register: vbox
  - name: Add the created VM to the inventory
    add_host:
      hostname: "{{ vbox.guest_ip }}"
      groupname: vbox
  - name: Wait for the VM to be reachable
    wait_for_connection:
      host: "{{ vbox.guest_ip }}"
      port: 22
  - name: Configure the Samba AD DC on the VM
    include_role:
      name: configure_samba_ad_dc
    vars:
      ipaddr: "{{ vbox.guest_ip }}"
      subnet: "24"
      gateway: "192.168.56.1"
      dnssrv: "8.8.8.8"
      domain: "example.com"
      password: "secret"
  - name: Destroy the VM
    virtualbox:
      name: ansible-test-vm
      state: absent
